<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_ControlSource_HMI_Machine" Id="{b2bfe894-bd62-4bda-8587-75a7a69998f0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ControlSource_HMI_Machine EXTENDS FB_ControlSource_HMI

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="CyclicLogic" Id="{b9558393-f6df-424b-bb06-aa52f94a69ed}">
      <Declaration><![CDATA[METHOD CyclicLogic
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.CyclicLogic();

//Change the start permissive for the Machine 
MainPMLControl_Simplified.StartPermissive :=
    MainPMLControl_Standard.CurrentState = Tc3_PackML_V2.E_PMLState.ePMLState_Idle OR
    (MainPMLControl_Standard.CurrentState = Tc3_PackML_V2.E_PMLState.ePMLState_Held AND
    MAIN.Seedra.SpindleZ.CurrentState = E_PMLState.ePMLState_Idle);
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_ControlSource_HMI_Machine">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_ControlSource_HMI_Machine.CyclicLogic">
      <LineId Id="3" Count="6" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>