<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_JednorazowyBoolin" Id="{356d8125-8fe1-078d-20b2-469f11cd746b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FB_JednorazowyBoolin
VAR
	_boolin : BOOL;	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="boolin" Id="{98cbbf20-9582-01e7-042a-c965b007bd8b}">
      <Declaration><![CDATA[PROPERTY PUBLIC boolin : BOOL]]></Declaration>
      <Get Name="Get" Id="{72345106-28a3-00da-1829-e1ed8abe2fcf}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[boolin := _boolin;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{f2aed263-f562-0b2f-1362-c51dee4ea99e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[_boolin := boolin;]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>